/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gscript_terminal_ScreenBuffer */

#ifndef _Included_org_gscript_terminal_ScreenBuffer
#define _Included_org_gscript_terminal_ScreenBuffer
#ifdef __cplusplus
extern "C" {
#endif
#undef org_gscript_terminal_ScreenBuffer_NULL_POINTER
#define org_gscript_terminal_ScreenBuffer_NULL_POINTER 0LL
#undef org_gscript_terminal_ScreenBuffer_COPY_RESULT_SUCCESS
#define org_gscript_terminal_ScreenBuffer_COPY_RESULT_SUCCESS 0L
#undef org_gscript_terminal_ScreenBuffer_COPY_RESULT_WRONG_SIZE
#define org_gscript_terminal_ScreenBuffer_COPY_RESULT_WRONG_SIZE 1L
/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeCreate
 * Signature: (IIII)J
 */
JNIEXPORT jlong JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeCreate
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeAppend
 * Signature: (JB)V
 */
JNIEXPORT void JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeAppend
  (JNIEnv *, jclass, jlong, jbyte);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeLineFeed
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeLineFeed
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeEraseInLine
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeEraseInLine
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeEraseInScreen
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeEraseInScreen
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeSetGraphicsRendition
 * Signature: (J[I)V
 */
JNIEXPORT void JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeSetGraphicsRendition
  (JNIEnv *, jclass, jlong, jintArray);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeResize
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeResize
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeSetCursorRow
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeSetCursorRow
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeSetCursorCol
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeSetCursorCol
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeSetCursor
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeSetCursor
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeMoveCursor
 * Signature: (JII)V
 */
JNIEXPORT void JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeMoveCursor
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeGetTextColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeGetTextColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeGetBackColor
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeGetBackColor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeGetScreenRows
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeGetScreenRows
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeGetScreenCols
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeGetScreenCols
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeGetScreenTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeGetScreenTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeGetScreenFillTop
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeGetScreenFillTop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeGetCursorRow
 * Signature: (JZ)I
 */
JNIEXPORT jint JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeGetCursorRow
  (JNIEnv *, jclass, jlong, jboolean);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeGetCursorCol
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeGetCursorCol
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_gscript_terminal_ScreenBuffer
 * Method:    nativeGetRowData
 * Signature: (JIZLjava/nio/ByteBuffer;)Z
 */
JNIEXPORT jboolean JNICALL Java_org_gscript_terminal_ScreenBuffer_nativeGetRowData
  (JNIEnv *, jclass, jlong, jint, jboolean, jobject);

#ifdef __cplusplus
}
#endif
#endif
